package ReadTDN;

import javax.swing.JOptionPane;

public class JFrameUtama extends Master {

    
    public JFrameUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        peminjamanBtn = new javax.swing.JMenuItem();
        pengembalianBtn = new javax.swing.JMenuItem();
        pendaftaranBtn = new javax.swing.JMenuItem();
        editBtn = new javax.swing.JMenuItem();
        hapusBtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel3.setFont(new java.awt.Font("Trajan Pro 3", 1, 60)); // NOI18N
        jLabel3.setText("READTDN");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("SMART-LIBRARY");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel4)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(354, Short.MAX_VALUE))
        );

        jMenu1.setText("Pegawai");

        peminjamanBtn.setText("Peminjaman Buku");
        peminjamanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peminjamanBtnActionPerformed(evt);
            }
        });
        jMenu1.add(peminjamanBtn);

        pengembalianBtn.setText("Pengembalian Buku");
        pengembalianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengembalianBtnActionPerformed(evt);
            }
        });
        jMenu1.add(pengembalianBtn);

        pendaftaranBtn.setText("Pendaftaran Buku");
        pendaftaranBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendaftaranBtnActionPerformed(evt);
            }
        });
        jMenu1.add(pendaftaranBtn);

        editBtn.setText("Edit Buku");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });
        jMenu1.add(editBtn);

        hapusBtn.setText("Hapus Buku");
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });
        jMenu1.add(hapusBtn);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Admin");

        jMenuItem6.setText("Atur Setting");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Registrasi");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void peminjamanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peminjamanBtnActionPerformed
        JFramePinjamanBuku pinjamBuku = new JFramePinjamanBuku();
        pinjamBuku.setVisible(true);
        pinjamBuku.kembaliBtn.setVisible(false);
        pinjamBuku.dendaText.setVisible(false);
        pinjamBuku.listKembalikanBtn.setVisible(false);
        pinjamBuku.lblTotalDenda.setVisible(false);
    }//GEN-LAST:event_peminjamanBtnActionPerformed

    private void pengembalianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengembalianBtnActionPerformed
        JFramePinjamanBuku kembalikanBuku = new JFramePinjamanBuku();
        kembalikanBuku.totalBukuTxt.setVisible(false);
        kembalikanBuku.listTambahBtn.setVisible(false);
        kembalikanBuku.hitungBukuBtn.setVisible(false);
        kembalikanBuku.pinjamBtn.setVisible(false);
        kembalikanBuku.jLabel4.setVisible(false);
        kembalikanBuku.jLabel2.setText("Form Pengembalian Buku");
        kembalikanBuku.setVisible(true);
    }//GEN-LAST:event_pengembalianBtnActionPerformed

    private void pendaftaranBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendaftaranBtnActionPerformed
        JFramePendaftaranBuku1 daftarBuku = new JFramePendaftaranBuku1();
        daftarBuku.setVisible(true);
        daftarBuku.bEdit.setVisible(false);
        daftarBuku.bDelete.setVisible(false);
    }//GEN-LAST:event_pendaftaranBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        JFramePendaftaranBuku1 edit = new JFramePendaftaranBuku1();
        edit.setVisible(true);
        edit.jLabel1.setText("EDIT BUKU");
        edit.daftarBtn.setVisible(false);
    }//GEN-LAST:event_editBtnActionPerformed

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusBtnActionPerformed
        JFramePendaftaranBuku1 edit = new JFramePendaftaranBuku1();
        edit.setVisible(true);
        edit.jLabel1.setText("HAPUS BUKU");
        edit.daftarBtn.setVisible(false);
        
    }//GEN-LAST:event_hapusBtnActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JFrameSetting setting = new JFrameSetting();
        setting.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JFrameRegister registrasi = new JFrameRegister();
        registrasi.setVisible(true);
        registrasi.roleSelect.removeItemAt(2);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if(db.loggedInNamaUser.length() == 0) {
        JFrameLogin login = new JFrameLogin();
        login.registBtn.setVisible(false);
        login.setVisible(true);
        
        if(db.loggedInNamaUser.length() != 0) {
            JOptionPane.showMessageDialog(this, "Selamat Datang " + db.loggedInNamaUser);
            
            if(db.role.compareTo("Admin") == 0) {
                jMenu1.setVisible(false);
                jMenu2.setVisible(true);
            } 
            else if(db.role.compareTo("Pegawai") == 0) {
                jMenu1.setVisible(true);
                jMenu2.setVisible(false);
            }
            else {
                JOptionPane.showMessageDialog(this, "Anda gagal Login sebagai Admin atau Pegawai, Program akan dihentikan!");
                System.exit(0);
            }
        }else {
            JOptionPane.showMessageDialog(this, "Silahkan Login Terlebih Dahulu!");
        }
        
    }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editBtn;
    private javax.swing.JMenuItem hapusBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem peminjamanBtn;
    private javax.swing.JMenuItem pendaftaranBtn;
    private javax.swing.JMenuItem pengembalianBtn;
    // End of variables declaration//GEN-END:variables
}
